import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import "@ant-design/v5-patch-for-react-19";
import Navbar from "@/components/Navbar";
import CustomFooter from "@/components/CustomFooter";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <video
          autoPlay
          muted
          loop
          playsInline
          className="fixed top-0 left-0 w-full  h-full object-cover -z-10"
        >
          <source src="/space-bg.mp4" type="video/mp4" />
        </video>

        <AntdRegistry>
          <Navbar />

          {children}

          <CustomFooter />
        </AntdRegistry>
      </body>
    </html>
  );
}
